### ISSUE TITLE
`disnake.Member.status` and `disnake.Member.raw_status` not working well.

### ISSUE THREAD

**Issue by Victorsitou** [DisnakeDev/disnake#108]
### Summary

While trying to get user's status it returns offline in Slash Commands, even though the user isn't offline.

### Reproduction Steps

When trying to get user's status in a `@bot.command()` command it works well and it returns the correctly status, but when using it in a `@bot.slash_command`, it returns offline. (I don't know if it works well in context menus)

Also, it just works when you have both Members and Presences intents.

### Minimal Reproducible Code

```python
Prefix commands that I'm using:

@bot.command()
async def status(ctx):
    # This one works well
    await ctx.send(ctx.author.status)

Slash commands that I'm using:

@bot.slash_command(name="status")
async def status(
    inter: disnake.ApplicationCommandInteraction,
    user: disnake.Member = commands.Param(description="user"),
):
    # This one returrns offline
    await inter.response.send_message(f"Your status is {user.status}")

Extra comment: Using `disnake.ApplicationCommandInteraction.author.status` returns also offline.
```

### Expected Results

Get the user's status.

### Actual Results

Returning offline in Slash Commands.

### Intents

Presences and Members

Important comment:
It seems that using this way to use intents doesn't work (I may be wrong but at least for the code listed above didn't work)
```
intents = disnake.Intents()
intents.members = True
intents.presences = True
```

The way I used to use intents is this one:
```
intents = disnake.Intents.default()
intents.members = True
intents.presences = True
```

### System Information

- Python v3.10.0-final
- disnake v2.2.1-beta
    - disnake pkg_resources: v2.2.1
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by shiftinv** [comment]
Thanks!

`ApplicationCommandInteraction.author.status` always returning `offline` is a bug, happens due to the fact that the user/member isn't taken from cache and therefore doesn't have presence data:
https://github.com/DisnakeDev/disnake/blob/659966ee528cf36d87b66c3cf9b4967e318063d0/disnake/interactions/base.py#L158-L166

Similar issue for member parameters, as well as `UserCommandInteraction.target`, as they aren't taken from the cache either but created solely from the received data:
https://github.com/DisnakeDev/disnake/blob/659966ee528cf36d87b66c3cf9b4967e318063d0/disnake/interactions/application_command.py#L385-L389

A workaround in all cases is to call `get_member` to get the member from cache manually, but that should probably be fixed.

**Comment by Victorsitou** [comment]
> A workaround in all cases is to call `get_member` to get the member from cache manually, but that should probably be fixed.

Oh I see, thank you so much for your response!
