### ISSUE TITLE
Missing raise type on `Guild.fetch_member`

### ISSUE THREAD

**Issue by Isabe1le** [DisnakeDev/disnake#1088]
### Summary

`disnake.errors.NotFound` is raised when an improper user id is passed.

### Reproduction Steps

1. Call a `await guild.fetch_member(...)` with an invalid user id.

### Minimal Reproducible Code

```python
guild = ...
await guild.fetch_member(123)
```
```


### Expected Results

n/a

### Actual Results

n/a

### Intents

n/a

### System Information

```markdown
- Python v3.10.11-final
- disnake v2.9.0-final
    - disnake importlib.metadata: v2.9.0
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22621 AMD64
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This is a documentation update.

**Comment by shiftinv** [comment]
The fact that `NotFound` can be raised here is technically covered by the [`HTTPException` case](https://github.com/DisnakeDev/disnake/blob/634f25f3b92f0507b0b7a088b55ba891dd2fd758/disnake/guild.py#L2704-L2705) already. I agree that it could be clarified though, especially since `Client.fetch_user` also lists `NotFound` separately.
