### ISSUE TITLE
Forced `response.defer()`

### ISSUE THREAD

**Issue by jellytoaster** [DisnakeDev/disnake#150]
### Summary

The library sometimes complains about deferring an interaction

### Reproduction Steps

When creating a slash command, using it would log an error in a console about the interaction already being responded to, or not responded to or something.

### Minimal Reproducible Code

```python
@disnake.slash_command(
    name="do",
    description="stuff"
)
async def doStuff(inter):
    if (var):
       await inter.response.send_message("Random error here.", ephemeral=True")
    
    await inter.response.send_message("Success")
```

### Expected Results

The expected result is to the slash command sending "Success"

### Actual Results

The slash command sends "Random error here." and logs an error in the console

### Intents

dinake.Intents.all()

### System Information

- Python v3.8.9-final
- Disnake v2.2.0-beta
          - disnake pkg-resources: v2.2.0
- aiohttp v3.7.0.post0
- system info: Windows 7 6.1.7601

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

A slash command in my discord bot throws an error on `inter.response.defer()` in less than 3 seconds, so I think this isn't lag or a discord issue, and throw Unknown Interaction.

**Comment by Victorsitou** [comment]
If I understand correctly, are you trying to respond to an interaction twice? If so, then that isn't possible, since you can't respond to an interaction twice.

What you might want to use is [``inter.followup.send()``](https://disnake.readthedocs.io/en/latest/api.html#disnake.Interaction.followup), which sends a followup message if you already responded to an interaction.
![image](https://user-images.githubusercontent.com/67214928/142552549-5c446ddd-c308-43c2-9d48-b43f2052e7fb.png)

**Comment by thesadru** [comment]
I'm surprised this wasn't handled properly in your case but you should've seen a completely separate error for responding twice. 

If you were to actually read the error you got you'd find out that it may not only be caused by not deferring but sometimes also by responding twice. 
This of course is not something that the user should be forced to account for, but since the discord API gives such arbitrary errors for slash commands it's impossible to tell what went wrong most of the time.

**Comment by jellytoaster** [comment]
> If I understand correctly, are you trying to respond to an interaction twice? If so, then that isn't possible, since you can't respond to an interaction twice.
> 
> What you might want to use is [`inter.followup.send()`](https://disnake.readthedocs.io/en/latest/api.html#disnake.Interaction.followup), which sends a followup message if you already responded to an interaction. ![image](https://user-images.githubusercontent.com/67214928/142552549-5c446ddd-c308-43c2-9d48-b43f2052e7fb.png)

I'm not trying to respond twice. It only responds once.

**Comment by thesadru** [comment]
From that it simply seems like you forgot to handle stopping the command from continuing? I'd expect a return in your if statement but I assumed it was just a mistake while simplifying the code.

**Comment by jellytoaster** [comment]
> From that it simply seems like you forgot to handle stopping the command from continuing? I'd expect a return in your if statement but I assumed it was just a mistake while simplifying the code.
The actual command in the code has a return in it on the error. Besides, the error isn't supposed to even run.
