### ISSUE TITLE
does not play music

### ISSUE THREAD

**Issue by NESTOWL** [DisnakeDev/disnake#268]
### Summary

music bot doesn't work on newer versions of disnake

### Reproduction Steps

Music playback does not work on the latest version of disnake 2.3.0
Works only on version 2.1.2

### Minimal Reproducible Code

```python
The minimum reproducible code is here: https://wavelink.readthedocs.io/en/latest/wavelink.html
in the Getting Started section
```

### Expected Results

Music will play as on disnake 2.1.2

### Actual Results

Music does not work on the latest version

### Intents

disnake.Intents.all()

### System Information

- Python v3.10.0-candidate
- disnake v2.1.2-alpha
    - disnake pkg_resources: v2.1.2
- aiohttp v3.7.4.post0
- system info: Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by NESTOWL** [comment]
I'm closing this question as a solution to this problem has been found:
```
bot = commands.Bot(..., enable_debug_events=True)

...

@bot.event
async def on_socket_raw_receive(data):
    msg = disnake.utils._from_json(data)
    bot.dispatch("socket_response", msg)
```

**Comment by EQUENOS** [comment]
**Additional note:**
This bug is from discord.py 2.0, it's caused by one of the breaking changes. The event named `on_socket_response` was renamed to `on_socket_raw_receive` which only works if `enable_debug_events` kwarg of `discord.Client` is `True`. Since disnake inherits from discord.py 2.0, this bug exists here as well. One of the possible fixes is mentioned in the comment above.

**Comment by thesadru** [comment]
This is more of a wavelink issue rather than a day issue. I recommend switching to a more reliable library to avoid issues like these in the future.
