### ISSUE TITLE
Make disnake.interactions.Interaction a Generic

### ISSUE THREAD

**Issue by lightningyx** [DisnakeDev/disnake#421]
### Summary

I would like disnake.interactions.Interaction to be a Generic with the TypeVar being the type of .channel.

### What is the feature request for?

The core library

### The Problem

When I create a slash command like this,
```py
@bot.slash_command()
async def test(inter: disnake.ApplicationCommandInteraction):
```
I expect inter.channel to be of the type `TextChannel | Thread`.
But the inferred type is `TextChannel | Thread | VoiceChannel`

### The Ideal Solution

I propose to make `disnake.interactions.Interaction` a `Generic`,
which is the parent class of `disnake.ApplicationCommandInteraction`.
Therefore you can parameterize it in type annotations to state the type of `.channel` more precisely.

### The Current Solution

This is my current solution to avoid type-checking issues:
```py
@bot.slash_command()
async def test(inter: disnake.ApplicationCommandInteraction):
    if isinstance(inter.channel, disnake.TextChannel):
        ...
```

### Additional Context

I'm new to contributing on GtiHub so I could have made an error

**Comment by onerandomusername** [comment]
> I expect inter.channel to be of the type TextChannel | Thread.
But the inferred type is TextChannel | Thread | VoiceChannel

This is correct, inter.channel can be a voice channel due to an upcoming feature by discord. This shouldn't affect your code unless you're using threads. 

IIRC voice channels will be supporting everything that a text channel supports, except for threads.

Minor support for this was merged weeks ago as we have some users who have bots in servers with early access to it.
