### ISSUE TITLE
Guild permissions disables the bot owner to use the slash command when reloading the cog

### ISSUE THREAD

**Issue by ironman9356** [DisnakeDev/disnake#491]
### Summary

When you disable the command for other users via the guild_permissions decorator it disables the slash command for the owner

### Reproduction Steps

Reload the cog in which the slash command with the guild_permissions decorator is there 

### Minimal Reproducible Code

```python
#use this decorator
@commands.slash_command(name="reload", description="To reload a cog", guild_ids=[935371069647384648],
                            default_permission=False)
@commands.guild_permissions(935371069647384648, owner=True)
```

### Expected Results

It reloads the cog and you can use the slash command normally with the edited code

### Actual Results

it disables the slash command for the people who have the permission to use it 

### Intents

all

### System Information

- Python v3.8.12-final
- discord v2.5.0-alpha
    - discord pkg_resources: v2.5.0a4223+gc59882ea ( i forked this repo and use it for discord namespace ) 
- aiohttp v3.8.1
- system info: Linux 5.13.0-1024-gcp #29~20.04.1-Ubuntu SMP Thu Apr 14 23:15:00 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

When you unload and load the same cog the slash commands are not visible in the client but `bot.get_guild_slash_commands(935371069647384648)`   shows all of them

**Comment by shiftinv** [comment]
This does look like an API bug with application commands v2, your server ID is part of that experiment.
In my testing the command didn't even show up in the first place, however editing it resulted in it being displayed but greyed out, which is what you mentioned on Discord as well. I'm assuming that you reloading the cog triggered an edit, so the result is about the same.
I'll try to investigate more later, but for now you could either wait for permissions v2 where this hopefully isn't an issue, or use local checks instead of `@guild_permissions`.

**Comment by ironman9356** [comment]
[This](https://github.com/DisnakeDev/disnake/pull/405) fixes this issue ty
