### ISSUE TITLE
ci: drop pre-commit/action

### ISSUE THREAD

**Issue by onerandomusername** [DisnakeDev/disnake#852]
drop pre-commit/action

this action is unmaintained and uses node js 12 which is deprecated by GitHub. See annotations [here](https://github.com/DisnakeDev/disnake/actions/runs/3388788779).

**Comment by shiftinv** [comment]
The action is no longer marked as deprecated (as of https://github.com/pre-commit/action/commit/5f528da5c95691c4cf42ff76a4d10854b62cbb82).

In any case, migrating to [v3](https://github.com/pre-commit/action/releases/tag/v3.0.0) should be enough, since that version completely dropped nodejs and now only handles caching + running `pre-commit` without any special behavior.
