### ISSUE TITLE
On timeout listener

### ISSUE THREAD

**Issue by solumath** [DisnakeDev/disnake#992]
### Summary

Add `on_timeout_listener(...)`

### What is the feature request for?

disnake.ext.commands

### The Problem

There should be listener for when user is timed out. As it stands now there is only `on_member_update` which passes before and after member's `current_timeout`. 
But it is not logical that i quote from docs: "Called when a [Member](https://docs.disnake.dev/en/stable/api.html#disnake.Member) updates their profile." 
Users can't update their own timeout... Which suggests that there should be a listener for this. Or atleast if there is update to member then the member who did the changes should be passed alongside `before`, `after`.

### The Ideal Solution

Implement `on_timeout_update` which will listen to timeout updates for members or include interaction with the user who updated the user.

### The Current Solution

None

**Comment by shiftinv** [comment]
This is a documentation issue, imo. The wording could be improved, `... updates their profile` is no longer accurate.
A new `on_timeout_update` event seems unnecessary, and may cause more confusion since timeout expiry does not trigger a gateway event.

> then the member who did the changes should be passed along side `before`, `after`.

The user who modified the timeout is only retrievable through audit logs, it's unfortunately not part of the gateway event data.
